before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.Version=(polarislabs fork) {{.Version}}"

archives:
  - format: tar.gz
    files:
      - none*

changelog:
  sort: asc

brews:
  - tap:
      owner: polarislabs
      name: chamber
    description: CLI for managing secrets
    homepage: https://github.com/polarislabs/chamber
    license: MIT
