# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chamber < Formula
  desc "CLI for managing secrets"
  homepage "https://github.com/polarislabs/chamber"
  version "2.12.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/polarislabs/chamber/releases/download/v2.12.7/chamber_2.12.7_darwin_arm64.tar.gz"
      sha256 "ab2dd30f53452eaba29ec9bd74871c988cd708ad7d303628c8f96948d4b98e38"

      def install
        bin.install "chamber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/polarislabs/chamber/releases/download/v2.12.7/chamber_2.12.7_darwin_amd64.tar.gz"
      sha256 "c488474774d9e22fd9cd423176eacd60ef6b1fc2014692df0cb2fe2d66932759"

      def install
        bin.install "chamber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/polarislabs/chamber/releases/download/v2.12.7/chamber_2.12.7_linux_amd64.tar.gz"
      sha256 "1ad0ce75261b6a011652b4014583a01e7a0defd22d20ceea1140307032db693b"

      def install
        bin.install "chamber"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/polarislabs/chamber/releases/download/v2.12.7/chamber_2.12.7_linux_arm64.tar.gz"
      sha256 "27f6454441f674c6fd8ba4fdbd0f910bb15ee911bea10570c36b1631f1260f11"

      def install
        bin.install "chamber"
      end
    end
  end
end
