# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chamber < Formula
  desc "CLI for managing secrets"
  homepage "https://github.com/polarislabs/chamber"
  version "2.12.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/polarislabs/chamber/releases/download/v2.12.6/chamber_2.12.6_darwin_amd64.tar.gz"
      sha256 "61f41ec56852a91faf0bbdd9f4ea258860cf29decfad6a9bf46dadc0206b501a"

      def install
        bin.install "chamber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/polarislabs/chamber/releases/download/v2.12.6/chamber_2.12.6_darwin_arm64.tar.gz"
      sha256 "ebe4106b7708900b157ca25ea49835a9ebcef199acce9747525797282daf3712"

      def install
        bin.install "chamber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/polarislabs/chamber/releases/download/v2.12.6/chamber_2.12.6_linux_arm64.tar.gz"
      sha256 "4013591124ebde85d89f03c83de3f4166b6505d85c136cadfa73b372665c5b69"

      def install
        bin.install "chamber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/polarislabs/chamber/releases/download/v2.12.6/chamber_2.12.6_linux_amd64.tar.gz"
      sha256 "c34bdef18c5bd051ac435df291853a3aaf4b04f6aa59c79639c24b9958c5dac0"

      def install
        bin.install "chamber"
      end
    end
  end
end
